"""Numerical/causal tests of a world model, not agent capability studies."""

from dataclasses import replace

import numpy as np
import pytest
import torch

from information_boltzmann.world import GenerativeWorldLaw, PersistentWorld, WorldConfig
from information_boltzmann.world.model import DEFAULT_MATERIALS
from information_boltzmann.world.simulation import dissipate


def test_optimized_forces_match_shared_hamiltonian_and_parameter_gradients():
    law = GenerativeWorldLaw(WorldConfig(cutoff_hz=180))
    world = PersistentWorld(law)
    world.state.q[0, 2] = DEFAULT_MATERIALS[0].radius - .002
    world.state.eta[:] = [.0005, -.0007, .0003]
    rng = np.random.default_rng(21)
    world.state.wave[:] = rng.normal(0, 1e-6, len(world.state.wave))
    q, eta, wave = [torch.tensor(value, requires_grad=True) for value in
                    (world.state.q, world.state.eta, world.state.wave)]
    potential = law.potential(q, eta, wave)
    gradients = torch.autograd.grad(potential, (q, eta, wave), retain_graph=True)
    actual = world.interaction()
    # Runtime splits out exactly-solvable uncoupled harmonic potentials.
    modal_harmonic = world.parameters["mode_mass"] * (2 * np.pi * world.parameters["frequency_hz"]) ** 2 * world.state.eta
    wave_harmonic = world.config.air_density * world.parameters["omega_air"] ** 2 * world.state.wave
    np.testing.assert_allclose(actual[0], -gradients[0].detach().numpy(), rtol=1e-11, atol=1e-10)
    np.testing.assert_allclose(actual[1] - modal_harmonic, -gradients[1].detach().numpy(), rtol=1e-11, atol=1e-10)
    np.testing.assert_allclose(actual[2] - wave_harmonic, -gradients[2].detach().numpy(), rtol=1e-11, atol=1e-10)
    potential.backward()
    for name, parameter in law.named_parameters():
        if name.startswith("sqrt_"):
            continue  # loss parameters belong to R, not the Hamiltonian
        assert parameter.grad is not None and torch.isfinite(parameter.grad).all()
        assert parameter.grad.abs().sum() > 0


def test_loss_parameters_are_learnable_nonnegative_and_match_heat_rate():
    law = GenerativeWorldLaw(WorldConfig(cutoff_hz=180))
    world = PersistentWorld(law)
    s, p, c = world.state, world.parameters, world.config
    s.q[:, 2] = p["radius"] - .001
    s.p[:] = .1
    s.modal_p[:] = .003
    s.wave_p[:] = .001
    power = law.dissipation_power(*[torch.tensor(v) for v in (s.q, s.eta, s.p, s.modal_p, s.wave_p)])
    assert power.item() > 0
    power.backward()
    for name, parameter in law.named_parameters():
        if name.startswith("sqrt_"):
            assert torch.isfinite(parameter.grad).all() and parameter.grad.abs().sum() > 0
    dt = 1e-8
    heat = dissipate(s.q, s.eta, s.p, s.modal_p, s.wave_p, p["mass"], p["mode_mass"],
                     p["radius"], p["shape"], p["room"], p["contact_damping"],
                     p["tangential_damping"], p["mode_decay"], c.air_density,
                     float(p["body_drag"]), float(p["air_decay"]), dt)
    assert heat.sum() / dt == pytest.approx(power.item(), rel=1e-5)


def test_contact_changes_motion_and_material_through_one_potential():
    world = PersistentWorld(GenerativeWorldLaw(WorldConfig(cutoff_hz=180)))
    world.state.q[0, 2] = DEFAULT_MATERIALS[0].radius - .001
    force, modal_force, _, touch, _ = world.interaction()
    assert touch[0, 2] > 0
    assert force[0, 2] > 0
    assert modal_force[0] == pytest.approx(-world.parameters["shape"][0] * touch[0, 2])
    world.step(300)
    assert np.linalg.norm(world.state.wave) > 0  # generated by continuous coupling


def test_closed_quiet_world_generates_no_sound_without_excitation():
    materials = [replace(DEFAULT_MATERIALS[0], mode_decay=0)]
    world = PersistentWorld(GenerativeWorldLaw(WorldConfig(gravity=0, cutoff_hz=180), materials),
                            positions=np.array([[1., 1., 1.]]))
    audio = world.step(128)
    assert np.count_nonzero(audio) == 0
    assert np.count_nonzero(world.state.wave) == 0
    assert world.energy()["total"] == 0


def test_sensor_motion_changes_only_observation_and_impulse_accounts_work():
    world = PersistentWorld(GenerativeWorldLaw(WorldConfig(cutoff_hz=180)))
    world.state.wave[0] = 1e-4
    before = world.energy()["total"]
    first = world.pressure(world.ears())
    state = world.state.q.copy()
    world.set_listener([.5, 1.1, .9], .4)
    second = world.pressure(world.ears())
    assert not np.allclose(first, second)
    np.testing.assert_array_equal(world.state.q, state)
    assert world.energy()["total"] == before
    work = world.impulse(1, [.08, 0., .12])
    assert world.energy()["total"] - before == pytest.approx(work, abs=1e-12)
    assert world.external_work == work


def test_all_dissipation_has_exact_complementary_heat():
    world = PersistentWorld(GenerativeWorldLaw(WorldConfig(cutoff_hz=180)))
    s, p, c = world.state, world.parameters, world.config
    s.q[0, 2] = p["radius"][0] - .002
    s.p[:] = .1
    s.modal_p[:] = .004
    s.wave_p[:] = .001
    before = world.energy()["total"]
    heat = dissipate(s.q, s.eta, s.p, s.modal_p, s.wave_p, p["mass"], p["mode_mass"],
                     p["radius"], p["shape"], p["room"], p["contact_damping"],
                     p["tangential_damping"], p["mode_decay"], c.air_density,
                     c.body_drag, c.air_decay, .001)
    assert min(heat) >= -1e-15
    assert before - world.energy()["total"] == pytest.approx(heat.sum(), abs=1e-12)


def test_energy_residual_decreases_under_time_refinement():
    errors = []
    for rate in (4000, 8000):
        material = replace(DEFAULT_MATERIALS[0], frequency_hz=110)
        world = PersistentWorld(GenerativeWorldLaw(WorldConfig(sample_rate=rate, cutoff_hz=180), [material]),
                                positions=np.array([[1., 1., .25]]))
        world.step(int(.35 * rate))
        error = abs(world.snapshot()["balance_error"])
        errors.append(error)
        assert error / world.initial_energy < .02
    assert errors[1] < errors[0]


def test_wave_coupling_is_reciprocal_and_bad_sampling_is_rejected():
    world = PersistentWorld(GenerativeWorldLaw(WorldConfig(cutoff_hz=180)))
    world.state.eta[0] = .001
    force_from_material = world.interaction()[2]
    assert np.linalg.norm(force_from_material) > 0
    world.state.eta[:] = 0
    world.state.wave[:] = 1e-5
    assert np.linalg.norm(world.interaction()[1]) > 0
    with pytest.raises(ValueError, match="Nyquist"):
        WorldConfig(sample_rate=500, cutoff_hz=410)


def test_restart_from_checkpoint_preserves_world_time_heat_and_next_waveform(tmp_path):
    world = PersistentWorld(GenerativeWorldLaw(WorldConfig(cutoff_hz=180)))
    world.impulse(0, [.08, .03, .05])
    world.step(1000)
    checkpoint = tmp_path / "world.npz"
    world.save(checkpoint)
    continued = PersistentWorld.load(checkpoint)
    assert continued.world_id == world.world_id
    assert continued.steps == world.steps
    assert continued.external_work == world.external_work
    np.testing.assert_array_equal(continued.heat, world.heat)
    expected = world.step(128)
    actual = continued.step(128)
    np.testing.assert_array_equal(actual, expected)
    assert continued.snapshot()["balance_error"] == world.snapshot()["balance_error"]
